apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poker-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mysql.yaml
  - app.yaml
  - ingress.yaml

# Optional: Add common labels
commonLabels:
  app.kubernetes.io/name: poker-de-garagem
  app.kubernetes.io/managed-by: kustomize
